name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read package.json
        uses: zvonimirsun/read-package-version-actions@v2
        id: package-version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ctr.0x.pt
          username: robot$wga+wga-frontend
          password: ${{ secrets.CTR_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ctr.0x.pt/wga/wga-frontend:latest, ctr.0x.pt/wga/wga-frontend:${{ steps.package-version.outputs.version }}
